## ![alt text](https://www.iitk.ac.in/new/images/page-images/logo/redlogo.jpg)  URBAN SOUND CLASSIFICATION ![alt text](https://ismrititek.com/upcoming-events/iitk-2019-summer/images/IITK.png)

## Team Members(TEAM 42):

### Sayantan Das

### Sourav Kumar

### Rohit

### Satyabrata Maharana

### Deepak Kumar



## **CLONING TRAINING DATA FROM GITHUB**






In [ ]:
! git clone https://github.com/BUNTYSAYU/traindata

Cloning into 'traindata'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1279 (delta 1), reused 0 (delta 0), pack-reused 1274
Receiving objects: 100% (1279/1279), 3.26 GiB | 15.84 MiB/s, done.
Resolving deltas: 100% (115/115), done.
Checking out files: 100% (1502/1502), done.


## **IMPORTING ALL LIBRARIES REQUIRED**

In [ ]:
import librosa
import librosa.display
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Input, Dense, Dropout, Activation, Flatten
from keras import optimizers
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from keras.optimizers import SGD


Using TensorFlow backend.


## **CREATING PATHS WHERE THE DATA ARE PRESENT**

In [ ]:
precedeString_Train = '/content/traindata'
precedeString_Val = '/content/testdata'


## **OBTAINING TRAINING DATA AND CONVERT TO ONE-HOT-ENCODE**

In [ ]:
train = pd.read_csv(precedeString_Train + '/train.csv') #READING TRAINING CSV FILE


![alt text](https://cdn-images-1.medium.com/max/1200/1*dWnjn5LLS0j8St53ACwqSg.jpeg)




# Mel Frequency Cepstral Coefficients (Speech Processing)


## 1.    First the audio signal is divided into Time Frames.
## 2.    Cepstrum is the information of rate of change in spectral bands.
## 3.    Filter Bank is basically the frequencey scaling by which we can absorb both low and high frequencies
##4.    Fourier transform are the Feature vectors
    



In [ ]:
def parser_Train(row):   
    file_name = precedeString_Train + '/'+str(row.ID) + '.wav' #MAKING OUT THE FILE NAME FOR EXTRACTION
    try:
      X, sample_rate = librosa.load(file_name,res_type='kaiser_fast')  #LOAD AND EXTRACT FEATURES
      mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0) #MFCCS FEATURE USED TO ANALYZE THE FEATURES
    except Exception as e:
      print("Error encountered while parsing file: ", file_name)
      return None, None
    feature = mfccs
    
    label = row.CLASSES
    print(file_name)
    return pd.Series([feature,label])

In [ ]:
temp = train.apply(parser_Train, axis=1) #PARSING THROUGH ALL FILE NAMES
temp.columns = ['feature','label']

/content/traindata/train_0000.wav
/content/traindata/train_0000.wav
/content/traindata/train_0001.wav
/content/traindata/train_0002.wav
/content/traindata/train_0003.wav
/content/traindata/train_0004.wav
/content/traindata/train_0005.wav
/content/traindata/train_0006.wav
/content/traindata/train_0007.wav
/content/traindata/train_0008.wav
/content/traindata/train_0009.wav
/content/traindata/train_0010.wav
/content/traindata/train_0011.wav
/content/traindata/train_0012.wav
/content/traindata/train_0013.wav
/content/traindata/train_0014.wav
/content/traindata/train_0015.wav
/content/traindata/train_0016.wav
/content/traindata/train_0017.wav
/content/traindata/train_0018.wav
/content/traindata/train_0019.wav
/content/traindata/train_0020.wav
/content/traindata/train_0021.wav
/content/traindata/train_0022.wav
/content/traindata/train_0023.wav
/content/traindata/train_0024.wav
/content/traindata/train_0025.wav
/content/traindata/train_0026.wav
/content/traindata/train_0027.wav
/content/train

In [ ]:
X = np.array(temp.feature.tolist())
y = np.array(temp.label.tolist())
print(y[0])
print(y[500])
print(y[1000])
print(y[799])

lb2 = LabelEncoder()
y=lb2.fit_transform(y)
print(y[0])
print(y[500])
print(y[1000])
print(y[799])

lb = LabelEncoder()  #LABELENCODER IS USED TO CONVERT STRINGS TO UNIQUE NUMBERS
y = np_utils.to_categorical(y) #CONVERTING IN THE FORM OF ONE-HOT -ENCOCDE

babycry
others
glassbreak
gunshot
0
3
1
2


## CLONING TESTING DATA FROM GITHUB

In [ ]:
! git clone https://github.com/BUNTYSAYU/testdata

Cloning into 'testdata'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1049 (delta 2), reused 0 (delta 0), pack-reused 1042
Receiving objects: 100% (1049/1049), 2.18 GiB | 15.04 MiB/s, done.
Resolving deltas: 100% (271/271), done.
Checking out files: 100% (1502/1502), done.


## **OBTAINING TESTING DATA AND CONVERT TO ONE-HOT-ENCODE**

In [ ]:
validate = pd.read_csv(precedeString_Val + '/test.csv') #READING TEST CSV FILE 

In [ ]:
def parser_Val(row):    #SAME AS DONE IN CASE OF TRAINING, LOADING OF FILE AND EXTRACTING FEATURES USING MFCC
    file_name = precedeString_Val + '/' + row.ID + '.wav'
    try:
      # here kaiser_fast is a technique used for faster extraction
      val_X, sample_rate = librosa.load(file_name,res_type='kaiser_fast') 
      # we extract mfcc feature from data
      mfccs = np.mean(librosa.feature.mfcc(y=val_X, sr=sample_rate, n_mfcc=40).T,axis=0) 
    except Exception as e:
      print("Error encountered while parsing file: ", file_name)
      return None, None
    feature = mfccs
    label = row.CLASSES
    print(file_name)
    return pd.Series([feature,label])

In [ ]:
temp_Val = validate.apply(parser_Val, axis=1)
temp_Val.columns = ['feature', 'label']

/content/testdata/test_0000.wav
/content/testdata/test_0000.wav
/content/testdata/test_0001.wav
/content/testdata/test_0002.wav
/content/testdata/test_0003.wav
/content/testdata/test_0004.wav
/content/testdata/test_0005.wav
/content/testdata/test_0006.wav
/content/testdata/test_0007.wav
/content/testdata/test_0008.wav
/content/testdata/test_0009.wav
/content/testdata/test_0010.wav
/content/testdata/test_0011.wav
/content/testdata/test_0012.wav
/content/testdata/test_0013.wav
/content/testdata/test_0014.wav
/content/testdata/test_0015.wav
/content/testdata/test_0016.wav
/content/testdata/test_0017.wav
/content/testdata/test_0018.wav
/content/testdata/test_0019.wav
/content/testdata/test_0020.wav
/content/testdata/test_0021.wav
/content/testdata/test_0022.wav
/content/testdata/test_0023.wav
/content/testdata/test_0024.wav
/content/testdata/test_0025.wav
/content/testdata/test_0026.wav
/content/testdata/test_0027.wav
/content/testdata/test_0028.wav
/content/testdata/test_0029.wav
/content

In [ ]:
val_X = np.array(temp_Val.feature.tolist())
val_Y = np.array(temp_Val.label.tolist())


lb2 = LabelEncoder()
val_Y=lb2.fit_transform(val_Y)

val_Y = np_utils.to_categorical(val_Y) #CONVERT TEST_Y TO ONE HOT ENCODE
print(val_Y.shape)

(1500, 4)


## **CREATE SEQUENTIAL MODEL USING KERAS**

In [ ]:
num_labels = y.shape[1]
filter_size = 2    #FOR DECIDING NO. OF NEURONS IN OUTPUT LAYER


![alt text](http://d33wubrfki0l68.cloudfront.net/0b32029a0c0f19a062d57dd101d3c85148e505e2/d4843/images/tasks/challenge2017/task2_overview.png)

In [ ]:
#input_layer=Input(shape=(X.shape[1:]))
model = Sequential()

model.add(Dense(50, input_shape = (40,)))
model.add(Activation('relu'))

model.add(Dense(50))
model.add(Activation('relu'))


model.add(Dense(50))
model.add(Activation('relu'))


model.add(Dense(50))
model.add(Activation('relu'))

model.add(Dense(num_labels))
model.add(Activation('sigmoid'))



model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X,y, epochs=200,validation_split=0.1)

Train on 1350 samples, validate on 150 samples
Epoch 1/200
1350/1350 [==============================] - 1s 519us/step - loss: 3.4706 - acc: 0.7285 - val_loss: 3.7153 - val_acc: 0.7617
Epoch 2/200
1350/1350 [==============================] - 0s 163us/step - loss: 3.4488 - acc: 0.7359 - val_loss: 3.6348 - val_acc: 0.7733
Epoch 3/200
1350/1350 [==============================] - 0s 172us/step - loss: 3.4752 - acc: 0.7337 - val_loss: 3.6451 - val_acc: 0.7733
Epoch 4/200
1350/1350 [==============================] - 0s 178us/step - loss: 3.4418 - acc: 0.7435 - val_loss: 3.6669 - val_acc: 0.7733
Epoch 5/200
1350/1350 [==============================] - 0s 186us/step - loss: 3.4394 - acc: 0.7430 - val_loss: 3.6624 - val_acc: 0.7733
Epoch 6/200
1350/1350 [==============================] - 0s 200us/step - loss: 3.0740 - acc: 0.7337 - val_loss: 2.2592 - val_acc: 0.6733
Epoch 7/200
1350/1350 [==============================] - 0s 193us/step - loss: 1.0454 - acc: 0.7315 - val_loss: 2.1016 - val_acc: 0

In [ ]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 50)                2050      
_________________________________________________________________
activation_1 (Activation)    (None, 50)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                2550      
_________________________________________________________________
activation_2 (Activation)    (None, 50)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 50)                2550      
_________________________________________________________________
activation_3 (Activation)    (None, 50)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 50)                2550      
__________

## **PREDICTING BY PASSING THE val_X THROUGH THE MODEL AND THEN CREATING CONFUSION MATRIX**

In [ ]:
loss, accuracy = model.evaluate(val_X, val_Y,verbose=0)  # Evaluate the model
print('Accuracy :%0.3f'%accuracy)
print('Loss:%0.3f'%loss)


Accuracy :0.744
Loss:0.635


In [ ]:
pred_labels=model.predict(val_X)
cm=confusion_matrix(val_Y.argmax(axis=1),pred_labels.argmax(axis=1))
print(cm)

#babycry
#glassbreak
#gunshot
#others


[[ 26   2  14 202]
 [ 35   7  11 189]
 [ 16   6  16 190]
 [ 66  23  48 649]]


In [ ]:
f1_score(val_Y,pred_labels.round(),average=None)

array([0.09146341, 0.01520913, 0.08053691, 0.59965928])

## **CLONING OF EVALUATION DATA FROM GITHUB AND LIVE DEMO FOR EVENT DETECTION**

In [ ]:
! git clone https://github.com/BUNTYSAYU/live

Cloning into 'live'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 35 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (35/35), done.
Checking out files: 100% (29/29), done.


### class [0] represents babycry
### class [1] represents glassbreak
### class [2] represents gunshot
### class [3] represents others

In [ ]:

file_name = "/content/live/BABYCRY TRUE.wav"
test_X, sample_rate = librosa.load(file_name,res_type='kaiser_fast')
mfccs = np.mean(librosa.feature.mfcc(y=test_X, sr=sample_rate, n_mfcc=40).T,axis=0)
test_X = np.array(mfccs)
test_X = test_X.reshape((1, 40))
print(model.predict_classes(test_X))

[0]
